SERVICES = {
"corporate-ai-training": {
    "title": "Corporate AI Training for Leaders and Teams | Kunaal Naik",
    "description": "Hands-on corporate AI training that connects business problems, role-based workflows, verification, and responsible adoption.",
    "kicker": "Corporate AI training",
    "h1": "Build AI capability around <em>real work.</em>",
    "lede": "Practical workshops for leadership, operations, marketing, sales, HR, and cross-functional teams. Participants begin with business outcomes and real work, then learn the appropriate AI methods without needing a technical background.",
    "problem": "Most AI workshops create excitement but little operating change. Teams see impressive demos, then return to unclear policies, weak context, scattered prompts, and no shared method for deciding what to trust.",
    "outcomes": ["A business problem and measurable outcome defined before tool selection", "Role-specific workflows participants can apply immediately", "A repeatable method for briefing, supervising, and checking AI work", "A prioritized 30/60/90-day adoption backlog", "Clear human-approval and data-handling boundaries"],
    "formats": ["Executive AI briefing — strategy, governance, and portfolio decisions", "Direct trainer-led discovery and programme design", "Role-based workshop — hands-on workflows for one function", "AI workflow lab — teams redesign a live process", "Enablement programme — workshops, office hours, champions, and measurement"],
    "fit": "CHRO, L&D, transformation, business-unit, and functional leaders who need adoption—not another inspirational keynote.",
    "subject": "Corporate AI training enquiry",
},
"ai-automation-consulting": {
    "title": "AI Automation Consulting for Enterprises, SMBs and MSMEs | Kunaal Naik",
    "description": "Practical AI workflow consulting: identify high-value work, prototype safely, implement with owners, and measure business outcomes.",
    "kicker": "AI workflow consulting",
    "h1": "Automate the right work—<em>not everything.</em>",
    "lede": "A focused consulting path for enterprises, SMBs, and MSMEs: understand the business problem, data, people, and approvals first, then implement the smallest useful AI workflow without a bloated transformation programme.",
    "problem": "The usual failure mode is tool-first automation: buy software, automate an unstable process, discover missing data and approvals, then leave the team with a fragile workflow nobody owns.",
    "outcomes": ["A workflow inventory scored by value, feasibility, risk, and proof", "One bounded pilot with a named human owner", "Documented inputs, decisions, approvals, exceptions, and fallback", "A practical handover and team enablement plan", "Baseline and after-state measures for time, quality, rework, and risk"],
    "formats": ["AI workflow opportunity audit", "Fixed-scope workflow sprint", "Team implementation and handover", "Fractional AI enablement advisory"],
    "fit": "Owner-led businesses, functional leaders, and transformation teams that want a useful first win and a method they can reuse.",
    "subject": "AI workflow consulting enquiry",
},
"claude-cowork-training": {
    "title": "Claude Cowork Training and Enablement for Teams | Kunaal Naik",
    "description": "Claude Cowork training for teams: projects, files, multi-step work, supervision, verification, connectors, and safe reusable workflows.",
    "kicker": "Claude Cowork training",
    "h1": "Make Claude Cowork a <em>supervised teammate.</em>",
    "lede": "Help knowledge-work teams use Claude Cowork for multi-step work across files, research, analysis, documents, spreadsheets, and recurring tasks—without confusing fluent output with reliable work.",
    "problem": "Cowork can coordinate complex work, but capability alone does not create adoption. Teams need outcome contracts, context packs, reusable project instructions, decision boundaries, and disciplined checks.",
    "outcomes": ["A clear Cowork task loop: brief, plan, act, review, revise", "Role-specific examples using real-but-safe work", "Project instructions and reusable workflow patterns", "Verification checklists for research, documents, and analysis", "Governance guidance for files, connectors, approvals, and sensitive work"],
    "formats": ["Claude Cowork executive demonstration", "Hands-on team workshop", "Role-based workflow design lab", "Project and instruction setup sprint"],
    "fit": "Consulting, operations, marketing, research, finance, and leadership teams on Claude paid, Team, or Enterprise plans.",
    "subject": "Claude Cowork training enquiry",
},
"hermes-agent-training": {
    "title": "Hermes Agent Training, Setup and Business Workflows | Kunaal Naik",
    "description": "Hermes Agent setup and training for persistent memory, reusable skills, tools, schedules, channels, and governed business workflows.",
    "kicker": "Hermes Agent consulting",
    "h1": "Build an AI operating layer that <em>remembers.</em>",
    "lede": "Setup, training, and workflow design for teams and professionals who want a persistent AI agent with memory, reusable skills, tools, scheduled jobs, and cross-channel operation.",
    "problem": "A persistent agent is more powerful than a disposable chat—and more demanding. Poor memory, oversized instructions, unsafe tools, noisy schedules, and missing approval gates create operational debt quickly.",
    "outcomes": ["A clean Hermes profile, identity, memory, and model configuration", "Reusable skills for stable business procedures", "Approved tools and integrations with explicit boundaries", "Useful scheduled workflows that stay quiet when nothing changes", "A maintenance and review method your team can own"],
    "formats": ["Hermes setup and architecture session", "Personal AI operating system build", "Team skills and workflow workshop", "Persistent automation implementation sprint"],
    "fit": "Founders, consultants, operators, and technical teams ready to move beyond disposable chat into a governed, extensible agent.",
    "subject": "Hermes Agent setup and training enquiry",
},
"ai-agents-for-professionals": {
    "title": "AI Agents for Professionals and Founders | Kunaal Naik",
    "description": "Practical AI agent training for professionals and founders: business problems, workflows, delegation, verification, automation, and ethical services.",
    "kicker": "AI agents for professionals and founders",
    "h1": "Stop collecting prompts. Start <em>operating AI.</em>",
    "lede": "A practical learning path for professionals and founders who want to build useful AI workflows, delegate meaningful work, and keep judgment, quality, and accountability in human hands—without needing to begin as a programmer.",
    "problem": "Tool tutorials expire. Prompt libraries become clutter. The durable advantage is learning to choose outcomes, assemble context, decompose work, supervise execution, verify results, and preserve successful methods.",
    "outcomes": ["A portfolio of bounded AI workflows tied to real business or career problems", "The D4–LOOP method for delegation and supervision", "A reusable context and verification discipline", "A clear boundary between assistance and accountable judgment", "A roadmap from manual use to stable automation", "For founders, a responsible path from a proven workflow to a clearly scoped service—without income guarantees"],
    "formats": ["Professional AI fluency workshop", "AI operator cohort for teams", "Personal workflow portfolio sprint", "Founder workflow-to-service lab", "Leadership-to-operator alignment session"],
    "fit": "Mid-career professionals, managers, consultants, founders, solopreneurs, coaches, and operators who need working capability rather than another tools overview.",
    "subject": "AI agents for professionals enquiry",
},
}
