#!/usr/bin/env python3
"""The 23 structural pages from the competitor teardown.

Data only — rendered by build.py's existing service_body()/page() pipeline.
Kept out of build.py so that file stays readable; this is also the seam the
markdown article pipeline should replace later.

Each entry needs unique substance: a real workflow, a named artifact, a
governance note, and a measurement line. Template-swapped pages are exactly the
doorway pattern the teardown says to avoid.

Fields: title, description, kicker, h1, lede, problem, outcomes[], formats[],
fit, subject, and optionally faqs[(q,a)] and related[(label,url)].
"""

# ponytail: pricing left as drivers, not numbers. Kunaal must supply real bands
# before /corporate-ai-training-cost-india/ can carry them — inventing figures
# would be fabrication and would misprice him in public.
PRICE_TODO = ("Indicative fee bands are shared on the first call and in written "
              "proposals. What follows is what actually moves the number, so you "
              "can size a budget before speaking to anyone.")

FUNCTION_PAGES = {
"ai-training-for-finance-teams": {
    "title": "AI Training for Finance Teams | Kunaal Naik",
    "description": "Role-based AI training for finance and FP&A teams: variance commentary, budget narratives, reconciliation review, and audit-ready verification.",
    "kicker": "AI training for finance",
    "h1": "AI for finance work that <em>survives audit.</em>",
    "lede": "Hands-on training for controllers, FP&A, and finance operations. Teams practise on their own reporting cycle and leave with drafted workflows, a review standard, and explicit boundaries on what AI may never decide.",
    "problem": "Finance teams adopt AI for speed and inherit an audit problem. Numbers get restated in prose nobody traced, source workbooks drift from the narrative, and no one can show which figure a sentence came from when the auditor asks.",
    "outcomes": ["A variance-commentary workflow that cites the source cell or query for every claim",
                 "A month-end narrative draft loop with a named reviewer and sign-off step",
                 "A verification checklist covering arithmetic, period alignment, and restatement risk",
                 "Documented rules for what stays manual: accruals, judgements, disclosures",
                 "Baseline and after-state measures for close-cycle hours and rework"],
    "formats": ["Half-day finance leadership briefing", "Two-day FP&A workflow workshop",
                "Month-end close workflow lab on live (masked) data", "Enablement programme with post-close office hours"],
    "fit": "CFOs, finance controllers, FP&A leads, and shared-service finance teams under reporting pressure who cannot trade traceability for speed.",
    "subject": "AI training for our finance team",
    "faqs": [("Will AI be allowed to touch the numbers?",
              "No. The workflows draft commentary and summaries from figures the team has already produced and reconciled. Calculation stays in the ledger and the model; AI drafts the explanation, and every claim carries its source."),
             ("Do you work on our real data?",
              "Preferably on masked or prior-period data. The workflow must be realistic; the dataset does not need to be live. Data handling and access are agreed before the session.")],
    "related": [("Corporate AI training", "/corporate-ai-training/"),
                ("Claude Cowork for finance", "/claude-cowork-for-finance/"),
                ("Measuring training ROI", "/ai-training-roi-measurement/")],
},
"ai-training-for-hr-and-l-and-d": {
    "title": "AI Training for HR and L&D Teams | Kunaal Naik",
    "description": "AI training for HR and L&D: job descriptions, competency frameworks, onboarding content, and bias-aware review with human decision boundaries.",
    "kicker": "AI training for HR and L&D",
    "h1": "AI for people work, with <em>judgement intact.</em>",
    "lede": "Practical training for HR business partners, talent, and L&D teams. Participants rebuild one live people process with AI support and leave with a fairness-review step that survives scrutiny.",
    "problem": "HR is handed AI for drafting speed, then quietly uses it near hiring and performance decisions. That is where bias, privacy exposure, and employment risk concentrate — and where most training says nothing useful.",
    "outcomes": ["A job-description and competency drafting workflow with an inclusive-language review pass",
                 "An onboarding and policy content loop with a version-controlled source of truth",
                 "A written boundary list: AI never scores, ranks, or screens candidates or employees",
                 "A bias and privacy review checklist applied before anything reaches a candidate",
                 "Adoption measures for drafting time, revision cycles, and reviewer load"],
    "formats": ["HR leadership alignment briefing", "Two-day HR and L&D workflow workshop",
                "Competency-framework rebuild lab", "Train-the-trainer for internal L&D facilitators"],
    "fit": "CHROs, HR business partners, talent acquisition leads, and L&D teams who need drafting leverage without touching regulated decisions.",
    "subject": "AI training for our HR and L&D team",
    "faqs": [("Can AI help us screen candidates faster?",
              "Not in this programme. Screening, ranking, and scoring people is where legal and ethical exposure is highest, and the training explicitly rules it out. The gains are in drafting, structuring, and documentation."),
             ("Can our L&D team deliver this internally afterwards?",
              "Yes — that is the train-the-trainer format. Internal facilitators get the materials, the exercises, and the review standards, plus office hours during their first delivery.")],
    "related": [("Corporate AI training", "/corporate-ai-training/"),
                ("Choosing an AI trainer", "/how-to-choose-a-corporate-ai-trainer/"),
                ("RFP template", "/corporate-ai-training-rfp-template/")],
},
"ai-training-for-legal-teams": {
    "title": "AI Training for Legal and Compliance Teams | Kunaal Naik",
    "description": "AI training for in-house legal and compliance: clause comparison, research triage, obligation extraction, and privileged-material handling with human review.",
    "kicker": "AI training for legal",
    "h1": "AI for legal work, with <em>privilege protected.</em>",
    "lede": "Training for in-house counsel and compliance teams on where AI genuinely helps — comparison, triage, extraction, summarisation — and where it must not go near a matter.",
    "problem": "Legal teams face the sharpest version of the AI problem: fluent output that is confidently wrong, plus real confidentiality and privilege exposure. Generic prompt training makes both risks worse by increasing volume.",
    "outcomes": ["A clause-comparison workflow that surfaces differences for a lawyer to judge, never a verdict",
                 "An obligation and deadline extraction loop with citations back to the source clause",
                 "A confidentiality decision tree: what may be pasted, what never leaves the matter file",
                 "A hallucination-detection routine for citations, authorities, and quoted terms",
                 "Measures for review turnaround and volume handled per reviewer"],
    "formats": ["General counsel briefing", "Two-day legal workflow workshop",
                "Contract-review workflow lab", "Compliance documentation sprint"],
    "fit": "General counsel, in-house legal teams, contract managers, and compliance functions in regulated or contract-heavy businesses.",
    "subject": "AI training for our legal team",
    "faqs": [("How do you handle privileged material?",
              "It does not enter the training. Exercises use synthetic or fully redacted documents, and the session produces a written rule set for what may and may not be shared with any AI tool afterwards."),
             ("Will AI give us legal conclusions?",
              "No, and the workflows are designed so it cannot appear to. Output is framed as differences found, obligations extracted, and passages flagged — always with a citation and always for a lawyer to decide.")],
    "related": [("Corporate AI training", "/corporate-ai-training/"),
                ("Claude Cowork for legal", "/claude-cowork-for-legal/"),
                ("Agent governance", "/ai-agent-governance-and-guardrails/")],
},
"ai-training-for-operations": {
    "title": "AI Training for Operations Teams | Kunaal Naik",
    "description": "AI training for operations teams: SOP documentation, incident reporting, vendor communication, and exception handling with named process owners.",
    "kicker": "AI training for operations",
    "h1": "AI for operations that <em>documents itself.</em>",
    "lede": "Training for operations and process teams who own the work everyone else depends on. Participants turn one live process into documented, AI-supported steps with explicit exception routes.",
    "problem": "Operations runs on knowledge that lives in people's heads and expires when they leave. AI is usually pointed at automating the happy path, which is the least valuable and most fragile part of the process.",
    "outcomes": ["An SOP-drafting workflow that captures exceptions, not just the happy path",
                 "An incident and root-cause writing loop with a consistent structure",
                 "A vendor and stakeholder communication pattern with an approval gate",
                 "An exception register naming the human owner for every failure mode",
                 "Measures for documentation coverage, handover time, and repeat incidents"],
    "formats": ["Operations leadership briefing", "Two-day operations workflow workshop",
                "Live process documentation lab", "Implementation sprint for one bounded workflow"],
    "fit": "COOs, operations managers, process excellence teams, and shared-service leads carrying undocumented institutional knowledge.",
    "subject": "AI training for our operations team",
    "faqs": [("Will this replace our process people?",
              "The opposite. The training makes their knowledge explicit and reusable, which raises their leverage. The workflows all require a named human owner for exceptions."),
             ("What if our processes are not documented at all?",
              "That is the common starting point and it is fine. The first exercise is extracting a working SOP from how the team actually operates today.")],
    "related": [("Corporate AI training", "/corporate-ai-training/"),
                ("Claude Cowork for operations", "/claude-cowork-for-operations/"),
                ("AI workflow consulting", "/ai-automation-consulting/")],
},
"ai-training-for-sales-teams": {
    "title": "AI Training for Sales Teams | Kunaal Naik",
    "description": "AI training for sales teams: account research, call preparation, follow-up discipline, and CRM hygiene without generic automated outreach.",
    "kicker": "AI training for sales",
    "h1": "AI for selling that <em>does not sound automated.</em>",
    "lede": "Training for sales leaders and revenue teams on the preparation and follow-through where AI compounds — and away from the mass-personalisation that damages a premium brand.",
    "problem": "Sales teams reach for AI to send more, faster. That produces detectable template outreach, brand damage, and deliverability problems. The real gain is preparation quality and follow-through consistency.",
    "outcomes": ["An account and stakeholder research workflow producing a one-page pre-call brief",
                 "A call-preparation loop tied to the actual buying process, not a generic script",
                 "A follow-up discipline that captures commitments and next steps accurately",
                 "A CRM hygiene routine that keeps notes searchable and current",
                 "Measures for preparation time, follow-up latency, and pipeline data quality"],
    "formats": ["Revenue leadership briefing", "Two-day sales workflow workshop",
                "Pre-call brief and research lab", "Enablement programme with pipeline review sessions"],
    "fit": "CROs, sales directors, enterprise and consultative sales teams selling considered purchases where preparation beats volume.",
    "subject": "AI training for our sales team",
    "faqs": [("Can we use this to scale cold outreach?",
              "No. Mass-personalised outreach is explicitly out of scope — it is detectable, hurts deliverability, and cheapens a premium brand. The programme targets preparation and follow-through."),
             ("Does this integrate with our CRM?",
              "The workflows are designed around whatever CRM you already run. No new platform is required, and no data leaves your approved tools without agreement.")],
    "related": [("Corporate AI training", "/corporate-ai-training/"),
                ("AI workflow consulting", "/ai-automation-consulting/"),
                ("Measuring training ROI", "/ai-training-roi-measurement/")],
},
"ai-training-for-marketing-teams": {
    "title": "AI Training for Marketing Teams | Kunaal Naik",
    "description": "AI training for marketing teams: campaign planning, audience research, editorial quality control, and brand-voice consistency with human sign-off.",
    "kicker": "AI training for marketing",
    "h1": "AI for marketing without <em>brand drift.</em>",
    "lede": "Training for marketing leaders and content teams on using AI for research, planning, and drafting while keeping brand voice, factual accuracy, and editorial standards under human control.",
    "problem": "Marketing adopts AI fastest and pays for it in brand dilution. Volume rises, voice flattens, claims go out unverified, and the team ends up editing mediocre drafts instead of doing better thinking.",
    "outcomes": ["A campaign planning workflow that starts from audience evidence, not a blank prompt",
                 "A brand-voice specification the team and the tools both work from",
                 "An editorial QC pass covering claims, sources, and originality before publication",
                 "A research and synthesis loop for positioning and competitive input",
                 "Measures for output quality, revision cycles, and time from brief to approved asset"],
    "formats": ["Marketing leadership briefing", "Two-day marketing workflow workshop",
                "Brand-voice and editorial standards lab", "Campaign planning sprint"],
    "fit": "CMOs, marketing directors, content and brand leads who need leverage without turning the brand into generic AI output.",
    "subject": "AI training for our marketing team",
    "faqs": [("Will our content start sounding like everyone else's?",
              "That is the failure mode the programme is built to prevent. The first deliverable is a brand-voice specification, and the editorial QC pass explicitly checks for generic phrasing and unsupported claims."),
             ("Do you cover SEO and AI search visibility?",
              "At a working level — how answer engines select and cite sources, and what that means for content structure. Deep technical SEO is a separate consulting engagement.")],
    "related": [("Corporate AI training", "/corporate-ai-training/"),
                ("Claude Cowork for marketing", "/claude-cowork-for-marketing/"),
                ("Choosing an AI trainer", "/how-to-choose-a-corporate-ai-trainer/")],
},
"ai-training-for-engineering-teams": {
    "title": "AI Training for Engineering Teams and Managers | Kunaal Naik",
    "description": "AI training for engineering teams: reporting, planning, documentation, code review support, and agent workflows with verification and safety boundaries.",
    "kicker": "AI training for engineering",
    "h1": "AI for engineering beyond <em>autocomplete.</em>",
    "lede": "Training for engineering managers and technical teams already using AI coding tools, focused on the surrounding work — planning, documentation, review, reporting — and on agent workflows with real guardrails.",
    "problem": "Engineering teams adopt AI coding assistants individually and stall there. Nobody owns the review standard, generated code enters the codebase unexamined, and the non-coding work that consumes manager time stays manual.",
    "outcomes": ["A documentation workflow that keeps architecture notes current instead of stale",
                 "A planning and status-reporting loop that does not consume a manager's week",
                 "A review standard for AI-generated code, including what must be read line by line",
                 "An agent workflow for a bounded repetitive task, with permissions and a blast-radius limit",
                 "Measures for review throughput, documentation coverage, and rework rate"],
    "formats": ["Engineering leadership briefing", "Two-day technical workflow workshop",
                "Agent workflow implementation lab", "Team standards and review-practice sprint"],
    "fit": "VPs of engineering, engineering managers, tech leads, and platform teams who want team-level practice rather than individual tool adoption.",
    "subject": "AI training for our engineering team",
    "faqs": [("Our developers already use AI coding tools. What does this add?",
              "Individual tool use is not team capability. This addresses the shared standards — review, documentation, permissions, blast radius — plus the planning and reporting work that tools alone do not touch."),
             ("Is this framework or language specific?",
              "No. The workflows and standards apply across stacks. Exercises use your repositories and your review process where access permits.")],
    "related": [("Hermes Agent training", "/hermes-agent-training/"),
                ("Agent governance", "/ai-agent-governance-and-guardrails/"),
                ("When not to use an agent", "/when-not-to-use-an-ai-agent/")],
},
"ai-training-for-executive-teams": {
    "title": "AI Training for Executive and Leadership Teams | Kunaal Naik",
    "description": "Executive AI training: opportunity portfolios, governance, investment decisions, workforce implications, and a 90-day adoption roadmap.",
    "kicker": "AI training for executives",
    "h1": "AI decisions leaders can <em>defend.</em>",
    "lede": "Focused sessions for boards and executive teams that need a shared language for AI opportunity, risk, and investment — and a defensible answer on governance before spending scales.",
    "problem": "Executive AI education is either vendor theatre or abstract futurism. Neither helps a leadership team decide what to fund, what to govern, what to refuse, and what to tell the board next quarter.",
    "outcomes": ["An opportunity portfolio for the business, scored by value, feasibility, and risk",
                 "A governance position covering data, approvals, vendors, and accountability",
                 "An investment sequence that funds evidence before scale",
                 "A workforce and capability view: who needs what, and by when",
                 "A 90-day roadmap with named owners and decision gates"],
    "formats": ["Half-day executive briefing", "Board-level AI governance session",
                "Leadership alignment workshop", "Quarterly advisory cadence"],
    "fit": "Boards, CEOs, and executive committees making AI investment and governance decisions — not looking for a hands-on tool session.",
    "subject": "Executive AI briefing enquiry",
    "faqs": [("Is this hands-on?",
              "Only where it aids a decision. Executive sessions prioritise portfolio, governance, and sequencing. Hands-on practice belongs in the function-specific programmes."),
             ("Can you present to our board?",
              "Yes. Board sessions focus on governance posture, risk, and the investment case, with material you can reuse in board papers.")],
    "related": [("Corporate AI training", "/corporate-ai-training/"),
                ("Speaking and workshops", "/speaking-and-workshops/"),
                ("Agentic vs generative AI", "/agentic-ai-vs-generative-ai-for-business/")],
},
}

AGENTIC_PAGES = {
"claude-cowork-for-finance": {
    "title": "Claude Cowork for Finance Teams | Kunaal Naik",
    "description": "Claude Cowork setup for finance: variance commentary, board packs, reconciliation review, project instructions, and traceable verification.",
    "kicker": "Claude Cowork for finance",
    "h1": "Cowork for finance, <em>traceable by design.</em>",
    "lede": "Setup and enablement for finance teams using Claude Cowork on multi-step reporting work — with project instructions, source discipline, and a review gate before anything reaches a board pack.",
    "problem": "Cowork can carry a whole reporting cycle, which is exactly the risk. Without project instructions and source discipline, a fluent board narrative can drift from the workbook it claims to describe.",
    "outcomes": ["Project instructions encoding your chart of accounts, periods, and reporting conventions",
                 "A variance and board-pack workflow where every figure traces to a source file",
                 "A reconciliation review loop that surfaces anomalies for a human decision",
                 "Connector and file-access boundaries agreed before sensitive data is involved",
                 "A reviewer checklist covering period alignment, arithmetic, and restatement risk"],
    "formats": ["Cowork demonstration for finance leadership", "Project setup and instruction sprint",
                "Hands-on finance team workshop", "Reporting-cycle implementation with handover"],
    "fit": "Finance teams on Claude paid, Team, or Enterprise plans running recurring reporting cycles.",
    "subject": "Claude Cowork for our finance team",
    "faqs": [("How is this different from general Cowork training?",
              "The project instructions, verification checklist, and exercises are built around finance reporting specifically — periods, accounts, materiality, and audit traceability rather than generic knowledge work.")],
    "related": [("Claude Cowork training", "/claude-cowork-training/"),
                ("AI training for finance", "/ai-training-for-finance-teams/")],
},
"claude-cowork-for-legal": {
    "title": "Claude Cowork for Legal Teams | Kunaal Naik",
    "description": "Claude Cowork for legal teams: clause comparison, obligation extraction, matter-safe file handling, and citation verification with human review.",
    "kicker": "Claude Cowork for legal",
    "h1": "Cowork for legal, with <em>privilege boundaries.</em>",
    "lede": "Setup for in-house legal teams using Cowork across long documents — comparison, extraction, summarisation — with explicit rules on what may enter a project and what never leaves the matter file.",
    "problem": "Long-document work is where Cowork looks most impressive and where errors hide best. Legal teams need citation discipline and a confidentiality boundary before capability, not after an incident.",
    "outcomes": ["Project instructions encoding your playbook positions and drafting conventions",
                 "A clause-comparison workflow that reports differences with citations, never conclusions",
                 "An obligation and deadline register extracted with source references",
                 "A written confidentiality boundary for projects, files, and connectors",
                 "A citation and authority verification routine before anything is relied upon"],
    "formats": ["Cowork demonstration for general counsel", "Project setup and playbook encoding sprint",
                "Hands-on legal team workshop", "Contract-review implementation with handover"],
    "fit": "In-house legal and compliance teams on Claude paid, Team, or Enterprise plans handling contract volume.",
    "subject": "Claude Cowork for our legal team",
    "faqs": [("Can we put client or matter documents in a project?",
              "That is a decision the engagement helps you make deliberately, with a written rule set. Training itself uses synthetic or redacted documents.")],
    "related": [("Claude Cowork training", "/claude-cowork-training/"),
                ("AI training for legal", "/ai-training-for-legal-teams/")],
},
"claude-cowork-for-marketing": {
    "title": "Claude Cowork for Marketing Teams | Kunaal Naik",
    "description": "Claude Cowork for marketing: campaign briefs, content production, brand-voice instructions, editorial QC, and reusable project structure.",
    "kicker": "Claude Cowork for marketing",
    "h1": "Cowork for marketing, <em>on brand.</em>",
    "lede": "Setup for marketing teams using Cowork across campaign planning and content production, with brand voice encoded in project instructions and an editorial pass before anything publishes.",
    "problem": "Marketing teams get volume from Cowork immediately and lose voice just as fast. Without encoded brand standards and an editorial gate, output converges on generic and the team becomes a copy-editing queue.",
    "outcomes": ["Project instructions carrying brand voice, audience, and prohibited claims",
                 "A campaign brief-to-draft workflow with a defined review point",
                 "An editorial QC pass covering claims, sources, originality, and tone",
                 "Reusable project structure so each campaign does not start from zero",
                 "Measures for revision cycles and time from brief to approved asset"],
    "formats": ["Cowork demonstration for marketing leadership", "Brand-voice instruction sprint",
                "Hands-on marketing team workshop", "Campaign production implementation"],
    "fit": "Marketing, content, and brand teams on Claude paid, Team, or Enterprise plans producing recurring campaigns.",
    "subject": "Claude Cowork for our marketing team",
    "faqs": [("Can Cowork match our existing brand voice?",
              "To a useful degree, if the voice is specified concretely rather than described adjectivally. Producing that specification is part of the engagement.")],
    "related": [("Claude Cowork training", "/claude-cowork-training/"),
                ("AI training for marketing", "/ai-training-for-marketing-teams/")],
},
"claude-cowork-for-operations": {
    "title": "Claude Cowork for Operations Teams | Kunaal Naik",
    "description": "Claude Cowork for operations: SOP documentation, incident reporting, vendor communication, exception handling, and reusable project instructions.",
    "kicker": "Claude Cowork for operations",
    "h1": "Cowork for operations, <em>exceptions included.</em>",
    "lede": "Setup for operations teams using Cowork to document processes, write incident reports, and handle recurring communication — with exception routes and approval gates built in from the start.",
    "problem": "Operations documentation is perpetually out of date, and Cowork can generate a great deal of it quickly. Without exception handling and ownership, you get volumes of plausible documentation nobody trusts.",
    "outcomes": ["Project instructions carrying your process conventions and terminology",
                 "An SOP workflow that captures exceptions and escalation, not only the happy path",
                 "An incident and root-cause reporting loop with a consistent structure",
                 "A vendor and stakeholder communication pattern with an approval step",
                 "An exception register naming a human owner for each failure mode"],
    "formats": ["Cowork demonstration for operations leadership", "Process documentation sprint",
                "Hands-on operations team workshop", "Workflow implementation with handover"],
    "fit": "Operations, process excellence, and shared-service teams on Claude paid, Team, or Enterprise plans.",
    "subject": "Claude Cowork for our operations team",
    "faqs": [("Can it document a process we have never written down?",
              "Yes, and that is usually the highest-value starting point — extracting a working SOP from how the team actually operates, then reviewing it with the people who do the work.")],
    "related": [("Claude Cowork training", "/claude-cowork-training/"),
                ("AI training for operations", "/ai-training-for-operations/")],
},
"hermes-agent-for-consultants": {
    "title": "Hermes Agent for Consultants | Kunaal Naik",
    "description": "Hermes Agent setup for consultants: client research, proposal drafting, deliverable production, scheduled reporting, and per-client memory boundaries.",
    "kicker": "Hermes Agent for consultants",
    "h1": "An agent that remembers <em>every client.</em>",
    "lede": "Setup and workflow design for independent consultants and boutique firms: persistent per-client context, reusable delivery procedures, scheduled research, and strict separation between client engagements.",
    "problem": "Consultants rebuild context for every engagement and every deliverable. A persistent agent fixes that, but naive memory design leaks one client's context into another's work — a confidentiality failure, not an inconvenience.",
    "outcomes": ["A per-client memory and profile structure with enforced separation",
                 "Reusable skills for proposals, research briefs, and recurring deliverables",
                 "A scheduled research workflow that stays silent when nothing has changed",
                 "Tool and integration boundaries agreed per client engagement",
                 "A maintenance routine so the agent does not accumulate stale context"],
    "formats": ["Hermes setup and architecture session", "Per-client workflow design sprint",
                "Deliverable production implementation", "Ongoing advisory as the practice grows"],
    "fit": "Independent consultants, boutique consultancies, and fractional operators carrying several concurrent clients.",
    "subject": "Hermes Agent setup for my consulting practice",
    "faqs": [("How do you stop client data mixing?",
              "Separate profiles and memory scopes per client, with tool access granted per engagement rather than globally. The separation is a configuration decision made deliberately at setup."),
             ("Do I need to be technical?",
              "No, though comfort with a terminal helps. The setup session produces a working configuration and the documentation to maintain it.")],
    "related": [("Hermes Agent training", "/hermes-agent-training/"),
                ("Agent governance", "/ai-agent-governance-and-guardrails/")],
},
"hermes-agent-for-executives": {
    "title": "Hermes Agent for Executives | Kunaal Naik",
    "description": "Hermes Agent setup for executives: briefing preparation, inbox and calendar triage, scheduled intelligence, and delegated work with approval gates.",
    "kicker": "Hermes Agent for executives",
    "h1": "A persistent agent for <em>executive load.</em>",
    "lede": "Setup for senior leaders who want AI that already knows the context — the portfolio, the people, the priorities — and produces briefings and summaries on a schedule rather than on request.",
    "problem": "Executives get the least value from disposable chat because re-establishing context costs more than the answer saves. Persistent memory changes that, provided approval gates prevent an agent from acting in a leader's name.",
    "outcomes": ["A memory structure holding portfolio, priorities, and stakeholder context",
                 "A scheduled briefing workflow that reports only what changed",
                 "Preparation packs for recurring meetings and reviews",
                 "Explicit approval gates: nothing is sent or committed without confirmation",
                 "A quarterly review routine to keep memory accurate"],
    "formats": ["Executive setup and architecture session", "Briefing workflow design sprint",
                "Chief-of-staff enablement", "Quarterly advisory cadence"],
    "fit": "CEOs, founders, and senior leaders — often with an EA or chief of staff who will co-own the configuration.",
    "subject": "Hermes Agent setup for an executive workflow",
    "faqs": [("Will it send email as me?",
              "Only if you explicitly configure that, and the default posture is a hard approval gate. Drafting is delegated; sending is not."),
             ("Who maintains it?",
              "Usually an EA or chief of staff, trained during the engagement. The configuration is documented so it does not depend on the person who built it.")],
    "related": [("Hermes Agent training", "/hermes-agent-training/"),
                ("AI training for executives", "/ai-training-for-executive-teams/")],
},
"hermes-agent-for-founders": {
    "title": "Hermes Agent for Founders | Kunaal Naik",
    "description": "Hermes Agent setup for founders: the first workflows worth automating, cost control, scheduled operations, and knowing when not to build an agent.",
    "kicker": "Hermes Agent for founders",
    "h1": "The founder's agent, <em>scoped honestly.</em>",
    "lede": "Setup for founders and small teams who need leverage before they need headcount — starting from the few workflows genuinely worth automating, and refusing the ones that are not.",
    "problem": "Founders automate the interesting problem rather than the expensive one, then maintain an agent that saves less time than it consumes. Selection discipline matters more than capability here.",
    "outcomes": ["A ranked shortlist of candidate workflows, with the rejected ones and reasons",
                 "Two or three implemented workflows with named owners and failure routes",
                 "A cost model covering tokens, model routing, and what to cap",
                 "Scheduled operations that stay quiet unless something needs attention",
                 "A stop rule: when to retire an agent instead of maintaining it"],
    "formats": ["Founder setup and prioritisation session", "Implementation sprint for the first workflows",
                "Small-team enablement workshop", "Advisory as the company scales"],
    "fit": "Founders, solo operators, and small teams under ten people where the founder is still the bottleneck.",
    "subject": "Hermes Agent setup for my company",
    "faqs": [("What if none of my workflows are worth automating?",
              "Then the honest answer is to say so, and the session will. Selection is the valuable part; building an agent for unstable, low-frequency work costs more than it returns."),
             ("How much does running an agent cost?",
              "It depends on model routing and volume, which is why cost modelling is an explicit deliverable rather than an afterthought.")],
    "related": [("Hermes Agent training", "/hermes-agent-training/"),
                ("When not to use an agent", "/when-not-to-use-an-ai-agent/")],
},
"ai-agent-governance-and-guardrails": {
    "title": "AI Agent Governance and Guardrails | Kunaal Naik",
    "description": "AI agent governance: permissions, approval gates, audit trails, blast-radius limits, data boundaries, and accountability for autonomous workflows.",
    "kicker": "AI agent governance",
    "h1": "Autonomy needs <em>accountability.</em>",
    "lede": "Advisory and enablement for organisations deploying agents that act, not just answer — covering permissions, approval gates, audit trails, and who is answerable when an agent gets it wrong.",
    "problem": "Governance frameworks written for chat assistants do not cover agents. An agent that can act has a blast radius, and most organisations discover they never defined one until something is sent, deleted, or committed.",
    "outcomes": ["A permission model scoped per agent, per tool, and per data source",
                 "Approval gates placed where consequences are irreversible",
                 "An audit trail sufficient to reconstruct what an agent did and why",
                 "A documented blast radius and containment plan per workflow",
                 "Named human accountability for every autonomous workflow in production"],
    "formats": ["Governance advisory session", "Agent risk and permission review",
                "Policy and standards drafting sprint", "Leadership and audit briefing"],
    "fit": "Risk, compliance, security, and technology leaders whose organisations are moving from AI assistants to agents that take action.",
    "subject": "AI agent governance advisory",
    "faqs": [("How is this different from our existing AI policy?",
              "Most AI policies govern what may be typed into a chat window. Agent governance has to cover actions, permissions, scheduling, and reversibility — a different problem."),
             ("Do we need this before deploying agents?",
              "Before deploying agents that can act, yes. Read-only agents are a much lighter case, and the review will say which yours are.")],
    "related": [("Hermes Agent training", "/hermes-agent-training/"),
                ("When not to use an agent", "/when-not-to-use-an-ai-agent/"),
                ("AI workflow consulting", "/ai-automation-consulting/")],
},
"when-not-to-use-an-ai-agent": {
    "title": "When Not to Use an AI Agent | Kunaal Naik",
    "description": "When an AI agent is the wrong tool: unstable processes, irreversible actions, low-frequency work, unclear ownership, and cheaper alternatives.",
    "kicker": "Agent selection",
    "h1": "Most work should <em>not</em> be an agent.",
    "lede": "A selection guide, and a deliberate counterweight to agent enthusiasm. The fastest way to waste money on AI is to build an autonomous workflow for work that should have stayed manual or become a simple script.",
    "problem": "Agent capability is being sold as universally applicable. It is not. Agents are expensive to build, easy to break, and require ongoing maintenance — costs that only pay back for a specific class of work.",
    "outcomes": ["A test for process stability: unstable processes must not be automated first",
                 "A reversibility check: irreversible actions need a human, not a gate you can skip",
                 "A frequency threshold below which automation never repays its build cost",
                 "An ownership requirement: no named owner means no agent",
                 "A cheaper-alternative check: a script, a template, or a form often wins"],
    "formats": ["Selection advisory session", "Workflow triage review",
                "Portfolio prioritisation workshop", "Second opinion on a proposed build"],
    "fit": "Leaders and teams holding a list of automation candidates who want the list shortened honestly before budget is committed.",
    "subject": "Agent selection and workflow triage",
    "faqs": [("Is this really a service?",
              "It is the first hour of most consulting engagements, and it saves the most money. Deciding not to build is a legitimate and frequently correct outcome."),
             ("What should we use instead?",
              "Often a template, a form, a database constraint, or a twenty-line script. The review names the cheapest thing that solves the actual problem.")],
    "related": [("AI workflow consulting", "/ai-automation-consulting/"),
                ("Agent governance", "/ai-agent-governance-and-guardrails/"),
                ("Agentic vs generative AI", "/agentic-ai-vs-generative-ai-for-business/")],
},
"agentic-ai-vs-generative-ai-for-business": {
    "title": "Agentic AI vs Generative AI for Business | Kunaal Naik",
    "description": "The difference between generative and agentic AI for business: what changes in cost, governance, risk, and capability when AI acts instead of answers.",
    "kicker": "Agentic vs generative AI",
    "h1": "When AI stops answering and <em>starts acting.</em>",
    "lede": "A decision briefing for leaders on the practical difference between generative and agentic AI — and why that distinction changes budgets, governance, and risk far more than it changes tooling.",
    "problem": "The terms are used interchangeably by vendors, which hides the part that matters: generative AI produces output a human then uses, while agentic AI takes actions with consequences. The governance and cost implications are not comparable.",
    "outcomes": ["A clear working distinction leadership can apply to any vendor pitch",
                 "The cost difference: per-request output versus ongoing autonomous operation",
                 "The governance difference: reviewing output versus constraining actions",
                 "A map of which of your workflows are genuinely agentic candidates",
                 "A sequencing view: what to prove with generative AI before funding agents"],
    "formats": ["Leadership decision briefing", "Board and executive session",
                "Vendor evaluation support", "Portfolio mapping workshop"],
    "fit": "Executives, technology leaders, and investment committees evaluating agentic AI proposals or vendor claims.",
    "subject": "Agentic AI briefing for our leadership team",
    "faqs": [("Is agentic AI just a marketing term?",
              "The marketing use is loose, but the underlying distinction is real and consequential: whether the system takes actions with side effects. That determines your governance and cost model."),
             ("Should we skip generative and go straight to agents?",
              "Rarely. Generative workflows prove the value and expose the data and process gaps cheaply. Agents built on unproven processes fail expensively.")],
    "related": [("Hermes Agent training", "/hermes-agent-training/"),
                ("Agent governance", "/ai-agent-governance-and-guardrails/"),
                ("AI training for executives", "/ai-training-for-executive-teams/")],
},
}

BUYER_PAGES = {
"corporate-ai-training-cost-india": {
    "title": "Corporate AI Training Cost in India | Kunaal Naik",
    "description": "What corporate AI training actually costs in India: the factors that drive fees, engagement shapes, what cheap programmes omit, and how to budget realistically.",
    "kicker": "Cost and budgeting",
    "h1": "What corporate AI training <em>actually costs.</em>",
    "lede": PRICE_TODO,
    "problem": "Most training pages hide pricing entirely, so L&D teams cannot budget and end up comparing a two-hour tool demonstration against a multi-week enablement programme as though they were the same purchase.",
    "outcomes": ["Audience seniority — executive sessions cost more to prepare than practitioner workshops",
                 "Customisation depth — generic decks are cheap; work built on your live processes is not",
                 "Delivery format — onsite, remote, and hybrid carry different cost structures",
                 "Whether implementation is included, or only training",
                 "Follow-through — office hours, champion support, and measurement extend the engagement",
                 "Group size and number of cohorts required for the population"],
    "formats": ["Executive briefing — half or full day", "Role-based workshop — one to two days per function",
                "Workflow implementation sprint — two to four weeks", "Enablement programme — multi-cohort with measurement"],
    "fit": "L&D, HR, and transformation teams building a budget or comparing proposals who need to know what drives the number.",
    "subject": "Corporate AI training budget discussion",
    "faqs": [("Why are fees not listed on this page?",
              "Because a number without scope is misleading. Fees depend on audience, customisation, format, and whether implementation is included. Indicative bands are shared on the first call and in every written proposal."),
             ("What is the minimum engagement?",
              "A one-day executive briefing or a two-week workflow sprint. Hourly tool demonstrations and single-session walkthroughs are not offered."),
             ("Why is the cheapest quote usually the most expensive?",
              "Low-cost programmes are generic by necessity. Nothing changes in the work, so the spend produces no adoption and the exercise repeats next year with a different vendor."),
             ("Do you work with SMBs and MSMEs?",
              "Yes, typically as a focused first workflow rather than an enterprise-wide programme. The engagement is scoped to what the business can absorb.")],
    "related": [("Corporate AI training", "/corporate-ai-training/"),
                ("Choosing an AI trainer", "/how-to-choose-a-corporate-ai-trainer/"),
                ("RFP template", "/corporate-ai-training-rfp-template/"),
                ("Measuring training ROI", "/ai-training-roi-measurement/")],
},
"how-to-choose-a-corporate-ai-trainer": {
    "title": "How to Choose a Corporate AI Trainer | Kunaal Naik",
    "description": "Criteria for selecting a corporate AI trainer: implementation evidence, role-based design, governance depth, verifiable proof, and the red flags to reject.",
    "kicker": "Selection criteria",
    "h1": "How to choose a trainer you <em>would rehire.</em>",
    "lede": "A buyer's guide written by a practitioner, including the criteria that predict adoption and the signals that predict an expensive, forgettable session.",
    "problem": "The market is crowded with trainers whose main evidence is participant counts and self-awarded superlatives. Neither predicts whether anything changes in the work after the room empties.",
    "outcomes": ["Implementation evidence — has the trainer shipped workflows, or only taught tools?",
                 "Role-based design — is the curriculum built per function, or one deck for everyone?",
                 "Governance depth — can they discuss permissions, approvals, and data boundaries credibly?",
                 "Verifiable proof — named, checkable outcomes rather than large round numbers",
                 "Follow-through — what happens in the 90 days after delivery",
                 "Refusal discipline — a trainer who says what AI should not do is more trustworthy"],
    "formats": ["Selection criteria you can put straight into an RFP",
                "Reference questions that reveal real capability",
                "Red flags: self-ranking lists, unverifiable totals, guaranteed outcomes, tool-inventory curricula",
                "A scoring approach for comparing proposals on the same basis"],
    "fit": "L&D, HR, procurement, and transformation leaders evaluating trainers or writing an RFP.",
    "subject": "Trainer selection and proposal discussion",
    "faqs": [("Is it a conflict of interest for a trainer to publish this?",
              "It is a stated bias, which is why the criteria are written to be checkable against any provider, including Kunaal. Use them to disqualify him if he does not meet them."),
             ("What is the single strongest signal?",
              "Whether the trainer has implemented the workflows they teach. Teaching-only providers cannot answer the operational questions that decide adoption."),
             ("What about certifications?",
              "They indicate exposure, not capability. Ask what the trainer has built and what broke.")],
    "related": [("Corporate AI training", "/corporate-ai-training/"),
                ("Training cost", "/corporate-ai-training-cost-india/"),
                ("RFP template", "/corporate-ai-training-rfp-template/")],
},
"ai-training-roi-measurement": {
    "title": "Measuring ROI From Corporate AI Training | Kunaal Naik",
    "description": "How to measure AI training ROI: adoption, time saved, quality, rework, risk, and review burden — with baselines captured before delivery.",
    "kicker": "Measurement",
    "h1": "Prove the training <em>changed the work.</em>",
    "lede": "A measurement approach for L&D and transformation teams who must justify AI spend with something more defensible than satisfaction scores.",
    "problem": "AI training is usually measured by attendance and happy sheets, which say nothing about whether the work improved. Meanwhile the baseline needed to prove improvement is never captured, so the question becomes unanswerable after the fact.",
    "outcomes": ["A baseline captured before delivery — without it, no improvement can be shown",
                 "Adoption measures: who is still using the workflow at 30, 60, and 90 days",
                 "Time measures on the specific workflow trained, not self-reported global estimates",
                 "Quality and rework measures, since faster output that needs more correction is a loss",
                 "Review burden — the verification cost AI adds, counted honestly",
                 "Risk measures: policy breaches, escalations, and near misses"],
    "formats": ["Measurement design session before a programme begins",
                "Baseline capture support", "90-day review and reporting",
                "Board and sponsor reporting pack"],
    "fit": "L&D, transformation, and finance sponsors accountable for demonstrating a return on AI training spend.",
    "subject": "Measuring AI training ROI",
    "faqs": [("Can you guarantee a productivity percentage?",
              "No, and any provider quoting one before seeing your processes is guessing. Outcomes depend on your workflows, data, and follow-through."),
             ("When should measurement be designed?",
              "Before delivery. Retrofitting measurement is the most common reason AI training cannot be justified afterwards."),
             ("Why count review burden as a cost?",
              "Because it is one. AI shifts effort from producing to verifying, and a measurement model that ignores that overstates the gain.")],
    "related": [("Corporate AI training", "/corporate-ai-training/"),
                ("Training cost", "/corporate-ai-training-cost-india/"),
                ("AI workflow consulting", "/ai-automation-consulting/")],
},
"corporate-ai-training-rfp-template": {
    "title": "Corporate AI Training RFP Template | Kunaal Naik",
    "description": "A free corporate AI training RFP template for L&D teams: scope, audience, outcomes, governance, proof requirements, and evaluation criteria.",
    "kicker": "RFP template",
    "h1": "An RFP that surfaces <em>real capability.</em>",
    "lede": "A structure L&D and procurement teams can use to compare AI training providers on the same basis — free to use, no email required, including questions Kunaal could fail.",
    "problem": "AI training RFPs typically ask for tool coverage and day rates, which every provider can answer identically. The questions that separate capable providers from confident ones are usually missing.",
    "outcomes": ["Audience and population definition, broken down by function and seniority",
                 "Required outcomes stated as changes in work, not topics covered",
                 "Governance requirements: data handling, approvals, and boundaries",
                 "Proof requirements: named, verifiable evidence rather than participant totals",
                 "Follow-through obligations for the 90 days after delivery",
                 "Evaluation criteria and scoring weights agreed before responses arrive"],
    "formats": ["Section-by-section RFP structure", "Question bank that exposes teaching-only providers",
                "Scoring rubric for comparing responses", "Reference-check question set"],
    "fit": "L&D, HR, and procurement teams running a competitive process for AI training or enablement.",
    "subject": "AI training RFP discussion",
    "faqs": [("Is the template gated?",
              "No. It is on this page, free to copy, with no form. Gating a buyer's tool to harvest emails is exactly the behaviour that makes procurement distrust vendors."),
             ("Can we use it to evaluate other providers?",
              "That is the intent. It is written to be provider-neutral, and Kunaal can be scored against it alongside everyone else.")],
    "related": [("Choosing an AI trainer", "/how-to-choose-a-corporate-ai-trainer/"),
                ("Training cost", "/corporate-ai-training-cost-india/"),
                ("Measuring training ROI", "/ai-training-roi-measurement/")],
},
}

GLOBAL_PAGES = {
"global-ai-training-delivery": {
    "title": "Global AI Training Delivery | Kunaal Naik",
    "description": "Global corporate AI training delivery: timezone bands, onsite and hybrid formats, contracting currency, and a dated record of delivery by region.",
    "kicker": "Global delivery",
    "h1": "Delivered where the <em>team actually is.</em>",
    "lede": "How international engagements work in practice — timezone coverage, onsite and remote formats, contracting and currency, and what changes when a programme spans regions.",
    "problem": "Most trainer sites answer international questions with a list of city pages. That tells a buyer nothing about timezone coverage, contracting, travel, or how a multi-region rollout is actually sequenced.",
    "outcomes": ["Timezone bands genuinely covered for live delivery, and the limits",
                 "Format guidance: when onsite justifies travel and when hybrid performs better",
                 "Contracting and currency options, including invoicing entity and taxes",
                 "Sequencing for multi-region rollouts so cohorts do not diverge",
                 "Localisation boundaries: what adapts per region and what stays standard"],
    "formats": ["Remote live delivery across Indian, Gulf, European, UK, and US timezone bands",
                "Onsite delivery with travel scoped in the proposal",
                "Hybrid programmes pairing remote practice with onsite intensives",
                "Multi-region enablement with staggered cohorts and a shared measurement model"],
    "fit": "Multinational L&D teams, GCCs, and distributed organisations needing consistent AI capability across regions.",
    "subject": "Global or multi-region AI training enquiry",
    "faqs": [("Which timezones can you deliver live?",
              "Indian, Gulf, European, and UK bands comfortably; US East Coast with a scheduling compromise. US West Coast live delivery is limited and usually better served by a hybrid design."),
             ("Can you invoice outside India?",
              "Yes. Contracting currency and invoicing entity are agreed during scoping, in INR or USD."),
             ("Do you publish a client list by country?",
              "A dated delivery ledger is shared during scoping. Public client naming only happens with written permission, so this page does not list logos.")],
    "related": [("Corporate AI training", "/corporate-ai-training/"),
                ("Speaking and workshops", "/speaking-and-workshops/"),
                ("Training cost", "/corporate-ai-training-cost-india/")],
},
}

STRUCTURAL = {**FUNCTION_PAGES, **AGENTIC_PAGES, **BUYER_PAGES, **GLOBAL_PAGES}

assert len(STRUCTURAL) == 23, f"expected 23 structural pages, got {len(STRUCTURAL)}"
