"""Contact, privacy, terms, 404 HTML bodies."""

CONTACT_FAQS = [
    ("What is the minimum engagement?",
     "Engagements start at a one-day executive briefing or a two-week workflow sprint. Kunaal does not take one-off hourly tool demonstrations or single-session ChatGPT walkthroughs."),
    ("Who is this for?",
     "Enterprise L&D and transformation teams, functional leaders with a budget, and owner-led businesses committing to implementation. Work is scoped per organisation, not sold as seats."),
    ("Do you deliver outside India?",
     "Yes. Delivery runs onsite, remote, and hybrid across Indian, Gulf, European, UK, and US timezone bands, contracted in INR or USD."),
    ("Is this training or implementation?",
     "Both, and that is the point. Training alone rarely changes the work. Engagements pair role-based training with one implemented, governed workflow and a measurement plan."),
    ("What do we need before starting?",
     "One valuable workflow worth improving, the people who own it, and an approver for data and tool access. A named business priority matters more than existing AI maturity."),
]


def build_legal(*, page_hero, mailto, faq_section, scorecard_cta, EMAIL, ENGAGEMENT_FLOOR, SOCIALS):
    contact = f'''{page_hero('Contact', 'Start with the work—not a <em>sales form.</em>', 'Email Kunaal directly about corporate AI training, AI workflow consulting, Claude Cowork, Hermes Agent, speaking, or partnerships.', 'Contact')}<section class="section"><div class="section-inner split"><div><p class="eyebrow">Email</p><h2><a href="mailto:{EMAIL}">{EMAIL}</a></h2><p class="section-intro">{ENGAGEMENT_FLOOR}</p><p class="section-intro">So the first reply is useful rather than a discovery call, include these five things:</p><ol class="list-clean"><li><strong>Organisation</strong> and your role</li><li><strong>Team size</strong> and the function involved</li><li><strong>Business priority or workflow</strong> you want improved</li><li><strong>Budget band</strong> and approval status</li><li><strong>Timeline</strong> and what success would look like</li></ol><a class="button button-primary" href="{mailto('Corporate AI training or consulting enquiry')}">Email with these details</a></div><div class="panel"><h3>Suggested subject lines</h3><ul class="list-clean"><li>Corporate AI training enquiry</li><li>AI workflow assessment for our business</li><li>Claude Cowork workshop for our team</li><li>Hermes Agent setup and training</li><li>Speaking or partnership enquiry</li></ul><h3>Not a fit</h3><ul class="list-clean"><li>Hourly tool demonstrations</li><li>Single-session ChatGPT walkthroughs</li><li>Certificate-only programmes</li><li>Unpaid pilots or spec work</li></ul><h3>Elsewhere</h3><div class="socials">{''.join(f'<a href="{u}">{n}</a>' for n,u in SOCIALS.items())}</div></div></div></section>{faq_section(CONTACT_FAQS)}{scorecard_cta("Not sure what to put in the email? Run the scorecard first and send the result. It tells Kunaal more in three minutes than a discovery call.")}'''

    privacy = f'''{page_hero('Privacy', 'What this site <em>collects, and why.</em>', 'This website has no contact form, account system, advertising network, or newsletter signup. It does run one third-party visitor-identification script, described below.', 'Privacy')}<section class="section"><div class="section-inner"><article class="prose"><h2>Information you choose to send</h2><p>If you email {EMAIL}, your email provider and Kunaal’s email provider process the message and associated metadata. Use email only for information you are comfortable sharing for the purpose of the enquiry.</p><h2>Website hosting</h2><p>The site is hosted on Vercel. Hosting infrastructure may process standard request information such as IP address, user agent, requested URL, and timestamps for security and service operation.</p><h2>Visitor identification</h2><p>This site loads a third-party script from Leadsy (<code>r2.leadsy.ai</code>) on every page. It is used to understand which organisations are visiting so that business enquiries can be followed up. Depending on the provider’s data sources, it may process your IP address, pages viewed, referrer, device and browser information, and attempt to associate that activity with a company or professional profile.</p><p>This is business-visitor identification, not an advertising network, and the data is not sold on from here. If you do not want to be identified this way, use a browser that blocks third-party scripts, an ad or tracker blocker, or a VPN. You can also email {EMAIL} to ask that any record associated with your visit be deleted.</p><p>Because this processing can involve personal data, it is treated as non-essential for visitors in the EU, UK, EEA, and Switzerland. If your browser reports a European timezone, the script does <strong>not</strong> load until you choose “Allow” on the consent notice, and your choice is remembered in your browser’s local storage. Choosing “Decline” means it never loads. Outside those regions the script loads on page view, as described above.</p><h2>Analytics and cookies</h2><p>No separate analytics or advertising cookies are intentionally set beyond what the visitor-identification script above requires. This policy will be updated before any further analytics or third-party embeds are added.</p><h2>External links</h2><p>Links to LinkedIn, YouTube, Instagram, GitHub, Data Science Masterminds, and other websites are governed by those services’ own policies.</p><h2>Questions or removal requests</h2><p>Email <a href="mailto:{EMAIL}">{EMAIL}</a>.</p></article></div></section>'''

    terms = f'''{page_hero('Terms', 'Clear boundaries for an <em>informational website.</em>', 'These terms cover use of the public KunaalNaik.com website. Separate written terms apply to paid engagements.', 'Terms')}<section class="section"><div class="section-inner"><article class="prose"><h2>Informational content</h2><p>Website content is general educational and marketing information. It is not legal, financial, security, employment, or investment advice and does not create a client relationship.</p><h2>No guaranteed outcome</h2><p>AI training and consulting outcomes depend on the organization, participants, data, systems, implementation, and ongoing use. No ranking, revenue, productivity, automation, or adoption result is guaranteed.</p><h2>Intellectual property</h2><p>Unless otherwise stated, original site copy, frameworks, and design are owned by Kunaal Naik. You may link to public pages and quote short excerpts with attribution.</p><h2>External tools</h2><p>Claude Cowork, Hermes Agent, n8n, and other product names belong to their respective owners. Mention does not imply endorsement or partnership.</p><h2>Engagements</h2><p>Scope, deliverables, confidentiality, data handling, fees, and commercial terms for any engagement must be agreed separately in writing.</p><h2>Contact</h2><p>Email <a href="mailto:{EMAIL}">{EMAIL}</a>.</p></article></div></section>'''

    not_found = f'''<section class="not-found"><div><strong>404</strong><h1>This page does not exist.</h1><p>The link may be outdated, or the page may have moved.</p><a class="button button-primary" href="/">Return home</a></div></section>'''
    return contact, privacy, terms, not_found
