"""Homepage HTML body."""

def build_home(*, mailto, scorecard_cta, cta):
    home = f'''<section class="hero"><div class="hero-grid"><div class="hero-copy"><p class="eyebrow">Corporate AI training · Workflow consulting</p><h1>Move from AI experiments to <em>working systems.</em></h1><p class="lede">Kunaal Naik helps leaders, teams, SMBs, and MSMEs identify one valuable workflow, train the people doing the work, implement the right AI approach, and measure whether it improved.</p><div class="hero-actions"><a class="button button-primary" href="{mailto('AI training or consulting enquiry')}">Discuss your AI priority</a><a class="button button-light" href="/ai-readiness-scorecard/">Take the 3-minute scorecard</a></div><div class="proof-strip"><div><strong>Trainer + implementer</strong><span>Capability, not tool theatre</span></div><div><strong>Enterprise-aware</strong><span>Governance and approval gates</span></div><div><strong>Global delivery</strong><span>Onsite, remote, and hybrid</span></div></div></div><div class="hero-portrait"><div class="portrait-frame"><img src="/assets/kunaal-naik.webp" width="719" height="720" alt="Kunaal Naik, corporate AI trainer and consultant"></div><div class="portrait-note">Founder · Data Science Masterminds<br>TEDx speaker</div></div></div></section>
<section class="section section-white"><div class="section-inner"><div class="section-head"><div><p class="eyebrow">Where Kunaal helps</p><h2>AI enablement for work that matters.</h2></div><p class="section-intro">The offer is deliberately practical: identify a valuable workflow, equip the people closest to it, implement safely, and prove whether it improved the work.</p></div><div class="service-grid">
<a class="service-card" href="/corporate-ai-training/"><span class="number">01 / TRAIN</span><h3>Corporate AI training</h3><p>Role-based workshops for leaders and functional teams, designed around real work rather than generic demos.</p><span class="arrow">→</span></a>
<a class="service-card" href="/ai-automation-consulting/"><span class="number">02 / IMPLEMENT</span><h3>AI workflow consulting</h3><p>A focused path from workflow inventory to a governed pilot and internal operating capability.</p><span class="arrow">→</span></a>
<a class="service-card" href="/claude-cowork-training/"><span class="number">03 / ENABLE</span><h3>Claude Cowork enablement</h3><p>Teach knowledge-work teams to brief, supervise, verify, and reuse multi-step AI work.</p><span class="arrow">→</span></a>
<a class="service-card" href="/hermes-agent-training/"><span class="number">04 / OPERATE</span><h3>Hermes Agent setup</h3><p>Persistent memory, skills, tools, schedules, and guardrails for a reusable AI operating layer.</p><span class="arrow">→</span></a>
<a class="service-card" href="/ai-agents-for-professionals/"><span class="number">05 / UPSKILL</span><h3>AI agents for professionals & founders</h3><p>Move beyond prompting into business problems, workflow design, delegation, verification, and responsible implementation.</p><span class="arrow">→</span></a>
<a class="service-card" href="/speaking-and-workshops/"><span class="number">06 / ALIGN</span><h3>Executive sessions & workshops</h3><p>Create a shared language for opportunity, risk, governance, and the next 90 days.</p><span class="arrow">→</span></a></div></div></section>
<section class="section"><div class="section-inner"><div class="section-head"><div><p class="eyebrow">Ways to start</p><h2>One workflow before a transformation.</h2></div><p class="section-intro">Choose the smallest engagement that can create a useful decision, a working artifact, or measurable adoption. Expand only after evidence exists.</p></div><div class="fit-grid"><div class="fit-card"><span class="tag">01 / ALIGN</span><strong>AI adoption briefing</strong><p>Executive alignment, live demonstrations, opportunity framing, and clear next decisions.</p></div><div class="fit-card"><span class="tag">02 / APPLY</span><strong>Hands-on workflow lab</strong><p>Use real artifacts to design two or three role-specific workflows with review boundaries.</p></div><div class="fit-card"><span class="tag">03 / IMPLEMENT</span><strong>AI Workflow Sprint</strong><p>A focused 2–4 week build: one workflow, the right agent or automation, guardrails, team training, and a measurement plan.</p></div><div class="fit-card"><span class="tag">04 / ADOPT</span><strong>90-day adoption partner</strong><p>Office hours, champions, workflow refinement, governance, and outcome reporting after launch.</p></div></div></div></section>
{scorecard_cta()}
<section class="section"><div class="section-inner"><div class="split"><div><p class="eyebrow">Two buying realities</p><h2>Enterprise discipline. Owner-led speed.</h2><p class="section-intro">Large organizations and growing businesses have different constraints. The method adapts without lowering the standard.</p></div><div class="fit-grid"><div class="fit-card"><strong>Enterprise teams</strong><p>Role-based adoption, governance, data boundaries, champions, and repeatable learning paths.</p></div><div class="fit-card"><strong>SMBs & MSMEs</strong><p>One high-value workflow first, a visible owner, a lean tool stack, and a practical handover.</p></div></div></div></div></section>
<section class="section section-dark"><div class="section-inner"><div class="section-head"><div><p class="eyebrow">The operating model</p><h2>Brief. Build. Verify. Transfer.</h2></div><p class="section-intro">AI fluency is not prompt volume. It is the ability to delegate responsibly, describe the work clearly, discern quality, and remain diligent about impact.</p></div><div class="process"><article><h3>Frame</h3><p>Define the outcome, user, constraints, source material, and what “done” means.</p></article><article><h3>Prototype</h3><p>Build the smallest workflow that can demonstrate value and expose risk.</p></article><article><h3>Verify</h3><p>Check facts, decisions, data handling, failure modes, and human approvals.</p></article><article><h3>Transfer</h3><p>Document the method, train the owner, and measure adoption and outcomes.</p></article></div></div></section>
<section class="section section-white"><div class="section-inner"><div class="section-head"><div><p class="eyebrow">Mission</p><h2>Make AI accessible, practical, and useful.</h2></div><p class="section-intro">The goal is not more tool knowledge. It is helping people understand the work, build useful capability, make better decisions, and keep human judgment accountable as AI scales.</p></div><div class="fit-grid"><div class="fit-card"><strong>Business first</strong><p>Start with the problem, user, decision, data, and metric before choosing technology.</p></div><div class="fit-card"><strong>Practical over perfect</strong><p>Build the smallest useful version, expose risk early, and improve after evidence exists.</p></div><div class="fit-card"><strong>Accessible, not careless</strong><p>Non-technical people can begin without removing verification, governance, or ownership.</p></div><div class="fit-card"><strong>Capability that stays</strong><p>Document the method, train the owner, and avoid permanent black-box dependency.</p></div></div></div></section>
{cta('What should AI improve in your organization?', 'Share the team, workflow, friction, and desired outcome. You will get a direct response by email.', 'AI training or workflow consulting enquiry')}'''
    return home
